/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package Purchase;

/**
 *
 * @author aamir7110
 */
public class MakingAPurchaseGUI extends javax.swing.JFrame {

    /**
     * Creates new form MakingAPurchaseGUI
     */
    public MakingAPurchaseGUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        PurchaseLabel = new javax.swing.JLabel();
        ProductLabel1 = new javax.swing.JLabel();
        ProductLabel2 = new javax.swing.JLabel();
        ProductLabel3 = new javax.swing.JLabel();
        NumberOfShirts = new javax.swing.JTextField();
        NumberOfGrapes = new javax.swing.JTextField();
        NumberOfApples = new javax.swing.JTextField();
        CalculateButton = new javax.swing.JButton();
        taxLabel = new javax.swing.JLabel();
        SubTotal = new javax.swing.JLabel();
        Total = new javax.swing.JLabel();
        InstructionLabel = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 153, 51));

        PurchaseLabel.setFont(new java.awt.Font("Comic Sans MS", 0, 48)); // NOI18N
        PurchaseLabel.setText("BUY SOMETHING");

        ProductLabel1.setText("# Of Apples");

        ProductLabel2.setText("#of Vegan Grapes");

        ProductLabel3.setText("# Of Shirts");

        NumberOfShirts.setText(" ");
        NumberOfShirts.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NumberOfShirtsActionPerformed(evt);
            }
        });

        NumberOfGrapes.setText(" ");

        NumberOfApples.setText(" ");

        CalculateButton.setText("Calculate");
        CalculateButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CalculateButtonActionPerformed(evt);
            }
        });

        taxLabel.setText("Tax:$0.00");

        SubTotal.setText("SubTotal:$0.00");

        Total.setText("Total Total:$0.00");

        InstructionLabel.setText("Enter The Number Of Each Item You Want To Purchase");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(154, 154, 154)
                .addComponent(InstructionLabel)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(55, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(PurchaseLabel)
                        .addGap(79, 79, 79))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(ProductLabel3)
                            .addComponent(ProductLabel2)
                            .addComponent(ProductLabel1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(NumberOfShirts, javax.swing.GroupLayout.DEFAULT_SIZE, 45, Short.MAX_VALUE)
                            .addComponent(NumberOfGrapes)
                            .addComponent(NumberOfApples))
                        .addGap(260, 260, 260)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(taxLabel)
                            .addComponent(SubTotal)
                            .addComponent(Total))
                        .addGap(46, 46, 46))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(CalculateButton)
                        .addGap(218, 218, 218))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(PurchaseLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(InstructionLabel)
                .addGap(36, 36, 36)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(ProductLabel1)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(NumberOfApples, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(taxLabel)))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ProductLabel2)
                    .addComponent(NumberOfGrapes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(SubTotal))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ProductLabel3)
                    .addComponent(NumberOfShirts, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Total))
                .addGap(18, 18, 18)
                .addComponent(CalculateButton)
                .addContainerGap(61, Short.MAX_VALUE))
        );

        jMenu1.setText("File");
        jMenu1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jMenuBar1.add(jMenu1);

        jMenu2.setText("Edit");
        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void NumberOfShirtsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NumberOfShirtsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NumberOfShirtsActionPerformed

    private void CalculateButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CalculateButtonActionPerformed
        
        //variable Declaration
        double Apples,Grapes,Shirts,subtotal,tax,total;
        double ApplePrice,GrapePrice,ShirtPrice;
        
        ApplePrice = 1.50;
        
        GrapePrice = 0.50;
        
        ShirtPrice = 5.00;
        
        Apples = Double.parseDouble(NumberOfApples.getText());
        
        Grapes = Double.parseDouble(NumberOfGrapes.getText());
        
        Shirts = Double.parseDouble(NumberOfShirts.getText());
        
        //some math
        subtotal = Apples*ApplePrice + Grapes*GrapePrice + Shirts*ShirtPrice;
        subtotal = subtotal*100;
        subtotal = Math.round(subtotal);
        subtotal = subtotal/100;
        
        tax = subtotal*0.13;
        tax = tax*100;
        tax = Math.round(tax);
        tax = tax/100;
        
        total = tax + subtotal;
        
        //setting text in gui
        
        SubTotal.setText("SubTotal:"+subtotal);
        Total.setText("Total:$"+total);
        taxLabel.setText("Tax:$"+tax);
    }//GEN-LAST:event_CalculateButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MakingAPurchaseGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MakingAPurchaseGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MakingAPurchaseGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MakingAPurchaseGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MakingAPurchaseGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton CalculateButton;
    private javax.swing.JLabel InstructionLabel;
    private javax.swing.JTextField NumberOfApples;
    private javax.swing.JTextField NumberOfGrapes;
    private javax.swing.JTextField NumberOfShirts;
    private javax.swing.JLabel ProductLabel1;
    private javax.swing.JLabel ProductLabel2;
    private javax.swing.JLabel ProductLabel3;
    private javax.swing.JLabel PurchaseLabel;
    private javax.swing.JLabel SubTotal;
    private javax.swing.JLabel Total;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel taxLabel;
    // End of variables declaration//GEN-END:variables
}
